PPWStory5/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from website.views import profile, registration, addEvent
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'^', include(('website.urls','website.urls'), namespace='website')),
	path('registration/', registration, name='registration'),
	path('addEvent/', addEvent, name='addEvent'),
    path('', profile, name='profile'),
    # url(r'^', include('website.urls')),
]

website/urls.py
from django.urls import path
from django.conf.urls import url
from .views import profile, registration, addEvent,saveproject
#url for app
urlpatterns = [

    path('', profile, name ='profile'),
	path('registration', registration, name='registration'),
    path('addEvent', addEvent, name = 'addEvent'),  

    path('save_project', saveproject, name ="saveproject")
]

website/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class PersonalSchedule(models.Model):
    date = models.DateTimeField(default=timezone.now);
    name = models.CharField(max_length=40);
    location = models.CharField(max_length=40);
    category = models.CharField(max_length=40);

website/forms.py
from django import forms
from .models import PersonalSchedule
import datetime

class Add_Event(forms.Form):
    error_messages = {
        'required': 'Please type',
    }
    pos_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Your name'
    }
    title_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Your Location'
    }
    description_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Your Category'
    }

    name = forms.CharField(label='', required=True, max_length=40, widget=forms.TextInput(attrs=pos_attrs))
    location = forms.CharField(label='', required=True, max_length=40, widget=forms.TextInput(attrs=title_attrs))
    category = forms.CharField(label='', required=True, max_length=40, widget=forms.TextInput(attrs=description_attrs))
    date = forms.DateField(initial=datetime.date.today)

website/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import Add_Event
from .models import PersonalSchedule

# Create your views here.
def profile(request):
	project = PersonalSchedule.objects.all()
	print("ads")
	print(project)
	response['project'] = project
	return render(request, "listLess.html",response)
def registration(request):

	return render(request, "Registration.html")
def addEvent(request):
	return render(request, "addEvent.html")

response = {}

def index(request):#!--duplicate-->
	print("asd")
	project = PersonalSchedule.objects.all()
	print(project)
	response['project'] = project

	html = 'listLess.html'
	return render(request, html, response)
#will refer to the normal webpage
def addEvent(request):
	response['title'] = 'Add Event to Calendar'
	response['addEvent_form'] = Add_Event()

	html = 'addEvent.html'

	return render(request, html, response)


#will respond with this html upon a request for add_event
def saveproject(request):
	form = Add_Event(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name']
		response['location'] = request.POST['location']
		response['category'] = request.POST['category']
		project = PersonalSchedule(name=response['name'], location=response['location'],category=response['category'])
		project.save()
		print("sukses")
		return HttpResponseRedirect(reverse('website:profile'))
	else:
		return HttpResponseRedirect('/')
#This is to save said information that has been stored

website/templates/Registration.html
<!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
      <link rel="stylesheet" type="text/css" href="style1.css">
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>SUM GO KAI, YOU GO DAI</title>
    </head>

    <body>
      <div class="container">
        <div class="title">
          <h4>Friends</h4>
        </div>
        <div class="frontText"><span class="flow-text">Are you a friend or a contact of Amal Adiguna?
          Please register now to notify him of your personal information and where he could contact you.</span></div>
      </div>
      <div class="row">
        <div class="col s4 offset-s2">Name: <input type="text" name="Name"></div>
        <div class="col s4 offset">Birth Date: <input type="date" name="Birthday"></div>
      </div>
      <div class="row">
        <div class="col s4 offset-s2">Username: <input type="text" name="Username"></div>
        <div class="col s4 offset">Email: <input type="email" name="email"></div>
      </div>
      <div class="row">
        <div class="col s4 offset-s2">Password: <input type="password" name="Password"></div>
        <div class="col s4 offset">Password Confirmation: <input type="password" name="PasswordConf"></div>
      </div>
      <div class="button">
        <button class="btn waves-effect waves-light black white-text" onclick="window.location.href='WebsiteStory2.html'" type="submit"><i class="material-icons left">add</i>Register Now!</button>
      </div>
      <!--JavaScript at end of body for optimized loading-->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js">
      </script>
    </body>
  </html>

website/templates/Story4-Base.html
<!DOCTYPE html>
{%load static%}
 <html>
   <head>
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
     <link rel="stylesheet" type="text/css" href="{% static 'style.css'%}"/>
     <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
     <title>A SERIOUS PROFILE PAGE</title>
   </head>
   <body>
	{% block content %}{% endblock %}
   </body>
 </html>

website/templates/addEvent.html
{% extends "Story4-Base.html" %}

{% block title %}
  Resume - Add Project
{% endblock %}

{% block content %}

<section id="Events">
	<div class="my-auto">
        	<form id="form" method="POST" action="{% url 'website:saveproject' %}">
	        	{% csrf_token %}
	          {{ title }}<!-- No .as_p karena itu buat forms only-->
	          {{ addEvent_form.as_p }}
	        	<input id="submit" type="submit" class="waves-effect waves-light btn-small" value="submit">
            <a class="waves-effect waves-light btn" href = "/">Back</a>
       		</form>
    </div>
</section>

{% endblock %}

website/templates/listLess.html
     {% extends 'Story4-Base.html'%}
	 {%load static%}
	 {%block content%}
 <!-- Dropdown Structure -->
 <ul id="dropdown1" class="dropdown-content">
	 <li><a href="#!">Registration</a></li>
	 <li><a href="#!">GookSpeak</a></li>
	 <li class="divider"></li>
	 <li><a href="#!">Market</a></li>
 </ul>
 <nav>
 <div class="nav-wrapper">
	 <a href="#!" class="brand-logo"></a>
	 <ul class="left hide-on-med-and-down">
	 <li><a href="{% url 'addEvent' %}">addEvent</a></li>
	 <li><a href="registration">Registration</a></li>
		 <!-- Dropdown Trigger -->
	 <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
	 </ul>
	 </div>
 <!-- Dropdown Structure -->
 </nav>
	 <div class="container">
     <div><h4 class="flow-text"><font size="7">Amal Adiguna</font></h4></div>
     <hr/>
		 <p>
      <div><font size="4"><span class="flow-text">Born:   29 April 1999<br/>
				Age:   19<br/>
				Birthplace: Jakarta, Indonesia</span></font></div>
		</p>
    <hr/>
    <br>
    <div><font size="4"><span class="flow-text">Sex/Gender:   Male</span></font></div>
    <div><font size="4"><span class="flow-text">Race:   Asian</span></font></div>
    <div><font size="4"><span class="flow-text">Occupation: Student</span></font></div>
    <div><font size="4"><span class="flow-text">Affiliation:   None</span></font></div>
    <div><font size="4"><span class="flow-text">Nationality:   Indonesia</span></font></div>
    <hr/>
    <div><font size="4"><span class="flow-text">Academic History:</span></font></div>
    <div><font size="4"><span class="flow-text">High School: SMAN 82</span></font></div>
    <div><font size="4"><span class="flow-text">University: University of Indonesia (ongoing)</span></font></div>
    <br>
    <hr1/>
    <div><font size="4"><span class="flow-text">Participated in the following MUN events:</span></font></div>
    <div><font size="4"><span class="flow-text">1. IMUN 2017</span></font></div>
    <div><font size="4"><span class="flow-text">2. NTUMUN 2018</span></font></div>
    <div><font size="4"><span class="flow-text">3. ALSA E-COMP 2018 (Most Outstanding Delegate)</span></font></div>
    <div><font size="4"><span class="flow-text">4. Grand General Assembly (Best Delegate)</span></font></div>
    <div><font size="4"><span class="flow-text">5. SMUN 2018</span></font></div>
    </div>
    <div class="wrapper">
      <div class="img">
        <img src="https://scontent.fcgk12-1.fna.fbcdn.net/v/t1.0-0/p552x414/36737332_10213176522189667_3006931321466388480_n.jpg?_nc_cat=104&oh=14643f4e27a236a0c3c7bff9128f64ba&oe=5C5F469A" alt="" class="responsive-image z-depth-4 circle">
      </div>

      <div class="bottomText">
        <span class="flow-text">I am a Computer Science student with <br>
          secondary interests in International <br>
          Relations and Economy.<br>I look forward to putting my skills<br>
           as a CS student to use.</span>
      </div>
      <div class="randomRectangle"></div>
      <div class="randomRectangle1"></div>
      <div class="randomRectangle2"></div>
			<div class="bottomTexteee">
				{% if project %}
					{% for data in project %}
						<div class="card-panel teal lighten-2">
							<div class="row">
								<div class="col s3 m3 l3"><p>Event Name:<br>{{data.name}}</p></div>
								<div class="col s1 m1 l3"><p>Date of Event:<br>{{data.date}}</p></div>
								<div class="col s1 m1 l3"><p>Category of Event:<br>{{data.category}}</p></div>
								<div class="col s3 m3 l3"><p>Location of Event:<br>{{data.location}}</p></div>
							</div>
						</div>
					{% endfor %}
				{% else %}
				{% endif %}
			</div>

    </div>
     <!--JavaScript at end of body for optimized loading-->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	{% endblock %}